# Generated by Django 4.2.3 on 2023-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_camera_type_alter_youtuber_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='subs_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
