# Generated by Django 4.2.3 on 2023-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='https://youtube.com', max_length=255),
            preserve_default=False,
        ),
    ]
