# Generated by Django 4.2.3 on 2023-07-17 07:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_description', ckeditor.fields.RichTextField()),
                ('about_us_image', models.ImageField(upload_to='media/promopitchr/%Y/%m/')),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.IntegerField()),
                ('facebook_link', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('youtube_link', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
    ]
